- name: HTTPD Configuration
  hosts: WEB
  tasks:

  - name: Install HTTPD Webserver
    package:
            name: "httpd"
            state: present

  - name: Install PHP (To Run PHP Code)
    package:
            name: "php"
            state: present   

  - name: Copy Webpage
    copy:
            content: "<pre>\n<?php\nprint `/usr/sbin/ifconfig eth0`;\n?>\n</pre>\n"
            dest: /var/www/html/index.php
    register: x
 
  - name: restart  webservice
    service:
            name: "httpd"
            state: restarted
    when: x.changed == true


- name: HAProxy Configuration
  hosts: LB
  tasks:

  - name: Install HAProxy
    package:
            name: "haproxy"
            state: present

  - name: Copying Config Jinja Template
    template:
            dest: "/etc/haproxy/haproxy.cfg"
            src: "haproxy.cfg.j2"
    notify: restart haproxy service

  handlers:
    - name: restart haproxy service
      service:
            name: "haproxy"
            state: restarted

